tools:
  cellranger: "/opt/cellranger-9.0.1/cellranger"

reference:
  transcriptome: "/media/data/NGS/refs/10X_sc/refdata-gex-GRCh38-2024-A"
  vdj: "/media/data/NGS/refs/10X_sc/refdata-cellranger-vdj-GRCh38-alts-ensembl-7.1.0"

resources:
  cellranger:
    threads: 32
    memory: 256  # RAM in GB

params:
  random_seed: 42
  QC:
    mito_perc: 10 # Percentage of mitochindrial genes (1-99) in the cell, cells with more than that would be discarded
    KNN: 30 # K nearest neighbors for QC clustering (usually 30)
    cluster_perc: 10 # QC would remove the clusters with more than this percentage threshold
